# Generated by Django 3.1.8 on 2023-02-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20230203_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='Mark',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
