# Generated by Django 3.1.8 on 2023-02-03 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20230203_0440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workschedule',
            old_name='Employee_No',
            new_name='Employee',
        ),
    ]
