# Generated by Django 3.1.8 on 2023-02-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20230203_0506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workschedule',
            old_name='EndTime',
            new_name='EndDate',
        ),
    ]
