# Generated by Django 3.1.8 on 2023-02-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20230203_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='WorkDate',
        ),
    ]
