# Generated by Django 3.1.8 on 2023-02-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_workschedule_workdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='EndTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='StartTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='EndDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='StartDate',
            field=models.DateField(),
        ),
    ]
