# Generated by Django 3.1.8 on 2023-02-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20230203_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Profile_Image',
            field=models.ImageField(null=True, upload_to='media/profile_pics/'),
        ),
    ]
