# Generated by Django 3.1.8 on 2023-02-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20230208_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='DateNow',
            field=models.DateField(),
        ),
    ]
