# Generated by Django 3.1.8 on 2023-02-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20230208_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='AttendanDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='InTime',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='OutTime',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
