# Generated by Django 3.1.8 on 2023-02-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20230210_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='status',
        ),
    ]
