# Generated by Django 3.1.8 on 2023-02-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_remove_workschedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='InTime',
            field=models.TimeField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='OutTime',
            field=models.TimeField(blank=True, max_length=256, null=True),
        ),
    ]
