# Generated by Django 3.1.8 on 2023-02-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20230211_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
