# Generated by Django 3.1.8 on 2023-02-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_employee_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Profile_Image',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
    ]
