# Generated by Django 3.1.8 on 2023-02-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20230212_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Profile_Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
