# Generated by Django 4.1.5 on 2023-02-15 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0020_auto_20230213_1221"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workschedule",
            name="Employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="index.employee"
            ),
        ),
    ]
